services:
  db:
    restart: 'no'

  redis:
    restart: 'no'

  app:
    restart: 'no'
    volumes:
      - nextcloud:/var/www/html:z

  web:
    restart: 'no'
    environment:
      VIRTUAL_HOST: 'test.sbcd.local'
      STAGE: local
    ports:
      - '80:80'
    volumes:
      - nextcloud:/var/www/html:z,ro

  cron:
    restart: 'no'
    volumes:
      - nextcloud:/var/www/html:z

networks:
  gateway:
  nextcloud: